services:
  nginx:
    image: nginx:alpine
    container_name: cine2025curso0git-main
    ports:
      - "8082:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
